# config/schema/commerce_strike.schema.yml
commerce_payment.commerce_payment_gateway.plugin.strike:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    currency:
      type: string
      label: 'Currency'
